global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'mysql_master'
    static_configs:
      - targets: ['mysqld-exporter-master:9104']

  - job_name: 'mysql_slave1'
    static_configs:
      - targets: ['mysqld-exporter-slave1:9104']

  - job_name: 'node_exporter_master'
    static_configs:
      - targets: ['node-exporter-master:9100']

  - job_name: 'node_exporter_slave'
    static_configs:
      - targets: ['node-exporter-slave:9100']

